deck_name = "deck:language-no::no-ordforråd"
model_name = "type-language-no-basic"
start_key = "production"
fields = [
    "production",
    "recognition",
 "note",
]
[audio_fields]
audio = "recognition"



# deck_name = "deck:language-no::no-verb"
# model_name = "type-language-no-verb"
# start_key = "infinitiv"
# fields = [
#     "infinitiv",
#     "infinitiv_uk",
#     "presens",
#     "preteritum",
#     "presens_perfektum",
#     "note",
# ]
# [audio_fields]
# audio_infinitiv = "infinitiv"
# audio_presens = "presens"
# audio_preteritum = "preteritum"
# audio_presens_perfektum = "presens_perfektum"



# deck_name = "deck:language-no::no-substantiv"
# model_name = "type-language-no-substantiv"
# start_key = "substantiv"
# fields = [
#     "substantiv",
#     "substantiv_uk",
#     "bestemt_ental",
#     "ubestemt_flertall",
#     "bestemt_flertall",
#     # "note",
# ]
# [audio_fields]
# audio_substantiv = "substantiv"
# audio_bestemt_ental = "bestemt_ental"
# audio_ubestemt_flertall = "ubestemt_flertall"
# audio_bestemt_flertall = "bestemt_flertall"
