deck_name = "language-no::no-ordforråd"
model_name = "type-language-no-basic"

[cards]
audio = "recognition"

[audio]
no = ["recognition"]
uk = ["production"]

[pdf]
fields = ["recognition", "production", "note"]
